[project]
id = "mls"
name = "Mach Language Server"
version = "0.3.2"
src = "src"
dep = "dep"
target = "native"

[targets.linux]
triple = "x86_64-pc-linux-gnu"
entrypoint = "main.mach"
artifacts = "out/linux"
output = "out/linux/bin/mls"
mode = "executable"
debug = true
optimize = false
emit-ast = true
emit-ir = true
emit-asm = true
emit-object = true
no-pie = false

[targets.darwin]
triple = "x86_64-apple-darwin"
entrypoint = "main.mach"
artifacts = "out/darwin"
output = "out/darwin/bin/mls"
mode = "executable"
debug = true
optimize = false
emit-ast = true
emit-ir = true
emit-asm = true
emit-object = true
no-pie = false

[targets.windows]
triple = "x86_64-pc-windows-msvc"
entrypoint = "main.mach"
artifacts = "out/windows"
output = "out/windows/bin/mls.exe"
mode = "executable"
debug = true
optimize = false
emit-ast = true
emit-ir = true
emit-asm = true
emit-object = true
no-pie = false

[deps.mach-std]
type = "remote"
path = "https://github.com/octalide/mach-std"
version = "branch/main"
