[project]
id = "mls"
name = "Mach Language Server"
version = "0.3.2"
dir_src = "src"
dir_dep = "dep"
dir_out = "out"
target = "native"

[targets.linux]
os = "linux"
isa = "x86_64"
abi = "sysv64"
mode = "executable"
entrypoint = "main.mach"
artifacts = "linux"
binary = "linux/bin/mls"

[deps.mach-std]
type = "remote"
path = "https://github.com/octalide/mach-std"
version = "branch/dev"

[deps.mach]
type = "remote"
path = "https://github.com/octalide/mach"
version = "branch/dev"
